engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 50e962421b67f542c5db54e9cd31327e
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- dist/
- scripts/
