language: node_js
node_js:
  - "node"
script:
  - npm run prettier
  - npm run eslint
  - npm run flow
  - npm run build
  - npm run test
  - npm run document
addons:
  code_climate:
      repo_token: c9d8a61877ca13e5985385d4f84d906fdb7638920ec9d0cfc624fa6312f9f1aa
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
